

stages:
  - test
build_test_modules:
  stage: test
  image: mcr.microsoft.com/playwright/python:v1.58.0-noble

  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

  cache:
    paths:
      - .cache/pip


  before_script:
    - set -euxo pipefail
    - apt-get update -y
    - apt-get install -y --no-install-recommends nodejs npm python3-venv
    - node --version
    - npm --version
    - python3 -m venv /usr/local/venv
    - /usr/local/venv/bin/python -m pip install --upgrade pip
    - /usr/local/venv/bin/pip install robotframework robotframework-browser robotframework-requests
    - /usr/local/venv/bin/rfbrowser init --skip-browsers


  script:
    - mkdir -p results
    #- /usr/local/venv/bin/robot -d results test/lifecycle.robot
    - /usr/local/venv/bin/robot -d results test/suites 
  artifacts:
    name: "robot-results-$CI_PIPELINE_ID"
    when: always
    paths:
      - results/
    expire_in: 7 days
  